### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-fpga#10]
We should make an examples section in the docs to make them more obvious/easier to find.

Maybe also put the videos of the lego robot somewhere.

**Comment by bmorcos** [comment]
There is a section that points to the examples and has instructions on how to run them. not sure if we want to give each example it's own full description like they do for Nengo?

**Comment by xchoo** [comment]
For the basic ones, yeah we should. My intention was to convert them into notebooks, which we can then use a built in notebook parser to convert them into doc pages.

**Comment by bmorcos** [comment]
Closed by #23
