### ISSUE TITLE
Check which versions CI uses to build docs

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-fpga#19]
The built docs at nengo.ai/nengo-fpga have the autoclass documentation rendering incorrectly for the API page. It is missing a space between the parameter/attribute name and the type.

Not sure if this is an issue with the sphinx or theme version we are using? the source code appears to be correctly formatted as far as I can tell.

**Comment by xchoo** [comment]
It fixed itself? Closing issue for now.
