### ISSUE TITLE
Fix DE1 compatibility with numpy 1.17

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo-fpga#38]
Unfortunately the DE1 still runs py2.7 and in numpy 1.17 they changed the pickle format from 2 to 3 for `np.savez_compressed`. This means our compressed params file is no longer readable on the DE1 side. 

For now we can just impose numpy<1.17, but we should find a solution going forward.

**Comment by xchoo** [comment]
This should be addressed now.
